insert into EQUIPAMENTO_SERIE (SERIE_EQUIPAMENTO ,SERIE_DATA_ENTRADA ,SERIE_DISPONIVEL )
values('aaa','20221002',true);


insert into EQUIPAMENTO_SERIE (SERIE_EQUIPAMENTO ,SERIE_DATA_ENTRADA ,SERIE_DISPONIVEL )
values('bbb','20221002',true);


insert into EQUIPAMENTO_SERIE (SERIE_EQUIPAMENTO ,SERIE_DATA_ENTRADA ,SERIE_DISPONIVEL )
values('ccc','20221002',true);

insert into EQUIPAMENTO_SERIE (SERIE_EQUIPAMENTO ,SERIE_DATA_ENTRADA ,SERIE_DISPONIVEL )
values('ddd','20221002',true);


insert into EMPRESA (CNPJ_EMPRESA ,CONTATO_EMPRESA ,ENDERECO_EMPRESA ,NOME_EMPRESA,EMPRESA_STATUS )
values('33.612.352/0001-57', '011 3614-1265', 'Endereço_1', 'Empresa_1',TRUE);

insert into EMPRESA (CNPJ_EMPRESA ,CONTATO_EMPRESA ,ENDERECO_EMPRESA ,NOME_EMPRESA,EMPRESA_STATUS )
values('42.283.528/0001-65', '012 2584-1563', 'Endereço_2', 'Empresa_2',TRUE);

insert into EMPRESA (CNPJ_EMPRESA ,CONTATO_EMPRESA ,ENDERECO_EMPRESA ,NOME_EMPRESA,EMPRESA_STATUS )
values('43.433.332/0001-72', '011 2456-2589', 'Endereço_3', 'Empresa_3',TRUE);

insert into EMPRESA (CNPJ_EMPRESA ,CONTATO_EMPRESA ,ENDERECO_EMPRESA ,NOME_EMPRESA,EMPRESA_STATUS )
values('16.437.628/0001-99', '012 2487-2964', 'Endereço_4', 'Empresa_4',TRUE);

insert into EMPRESA (CNPJ_EMPRESA ,CONTATO_EMPRESA ,ENDERECO_EMPRESA ,NOME_EMPRESA,EMPRESA_STATUS )
values('71.405.342/0001-30', '012 2365-1478', 'Endereço_5', 'Empresa_5',TRUE);

insert into TIPO_SERVICO (TIPO_SERVICO_DESCRICAO,TIPO_SERVICO_NOME)
values('Descrição_1', 'Outro Tipo');


insert into TIPO_SERVICO (TIPO_SERVICO_DESCRICAO,TIPO_SERVICO_NOME)
values('Descrição_2', 'Instalação');


insert into TIPO_SERVICO (TIPO_SERVICO_DESCRICAO,TIPO_SERVICO_NOME)
values('Descrição_3', 'Manutenção');


insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Instalação_1','2022-10-02', 1, 2);

insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Instalação_2','2022-10-02',NULL ,NULL);

insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Manuteção_1','2022-10-02',NULL, NULL);

insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Manuteção_2','2022-10-02', NULL, NULL);

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO, SERIE_EQUIPAMENTO )
values ('Equipamento parte interna', 'NPW LTDA', 'Câmera MTDC30W',  'aaa');

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO, SERIE_EQUIPAMENTO )
values ('Equipamento parte interna', 'PZA LTDA', 'Sensor BDC40E',  'bbb');

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO,  SERIE_EQUIPAMENTO )
values ('Equipamento parte externa', 'BTL LTDA', 'Câmera DDEEX20D',  'ccc');

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO,  SERIE_EQUIPAMENTO )
values ('Equipamento parte externa', 'KNC LTDA', 'Sensor NHFSEX70E',  'ddd');


insert into USUARIO(nome_usuario,usuario_status,codigo_empresa)
values( 'José',true, 1);

insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Instalação_1','2022-10-02', 1, NULL);

insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Instalação_2','2022-10-02',NULL ,NULL);

insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Manuteção_1','2022-10-02',NULL, NULL);

insert into SERVICO (SERVICO_DESCRICAO, SERVICO_DATA_INCLUSAO,CODIGO_EMPRESA, TIPO_SERVICO_CODIGO)
values('Nova Manuteção_2','2022-10-02', NULL, NULL);

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO,  SERIE_EQUIPAMENTO )
values ('Equipamento parte interna', 'NPW LTDA', 'Câmera MTDC30W',  'aaa');

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO,  SERIE_EQUIPAMENTO )
values ('Equipamento parte interna', 'PZA LTDA', 'Sensor BDC40E',  'bbb');

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO,  SERIE_EQUIPAMENTO )
values ('Equipamento parte externa', 'BTL LTDA', 'Câmera DDEEX20D',  'ccc');

insert into EQUIPAMENTO(DESCRICAO_EQUIPAMENTO, FABRICANTE_EQUIPAMENTO, NOME_EQUIPAMENTO,  SERIE_EQUIPAMENTO )
values ('Equipamento parte externa', 'KNC LTDA', 'Sensor NHFSEX70E',  'ddd');



insert into CHAMADO (CRITICIDADE_CHAMADO ,DATA_CHAMADO ,DESCRICAO_CHAMADO, ENCERRAMENTO_CHAMADO , SITUACAO_CHAMADO ,SOLUCAO_CHAMADO ,TIPO_CHAMADO, CODIGO_USUARIO )
values('Baixa', '20221006','Chamado novo', null, 'aberto', '', 1,1 );