insert into EQUIPAMENTO_SERIE (SERIE_EQUIPAMENTO ,SERIE_DATA_ENTRADA ,SERIE_DISPONIVEL )
values('aaa',null,true)

insert into EMPRESA (CNPJ_EMPRESA ,CONTATO_EMPRESA ,ENDERECO_EMPRESA ,NOME_EMPRESA )
values('12345', '1231241', 'fsadfsd', 'qualquer1')

insert into EMPRESA (CNPJ_EMPRESA ,CONTATO_EMPRESA ,ENDERECO_EMPRESA ,NOME_EMPRESA )
values('12345', '1231241', 'fsadfsd', 'qualquer2')

insert into TIPO_SERVICO (TIPO_SERVICO_DESCRICAO,TIPO_SERVICO_NOME  )
values('desc', 'qaul')


insert into TIPO_SERVICO (TIPO_SERVICO_DESCRICAO,TIPO_SERVICO_NOME  )
values('desc', 'Instalação')


insert into TIPO_SERVICO (TIPO_SERVICO_DESCRICAO,TIPO_SERVICO_NOME  )
values('desc', 'Manutenção')

